export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const SET_ADMIN_PERMISSIONS = 'SET_ADMIN_PERMISSIONS';

export const SET_LOGIN_MODE = 'SET_LOGIN_MODE';
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
